services:
  prime95:
    # build: .
    image: ghcr.io/arthur2500/prime95:latest
    container_name: prime95
    restart: no
    environment:
      PRIME95_FLAGS: "-d -t"
    # volumes:
    # - ./prime95/prime.txt:/opt/prime95/prime.txt
    # - ./prime95/results.txt:/opt/prime95/results.txt